### ISSUE TITLE
Data - Map of polygon layers

### ISSUE THREAD

**Issue by Ludee** [openego/oeplatform#113]
While point layers like power plants or substations work quite good polygon layers like borders are not displayed in the map.

**Comment by MGlauer** [comment]
This is seems to be a missing feature in recline.js. I will try to extend this tool as I got some time to my hands.

**Comment by wolfbunke** [comment]
Hey @MGlauer, for one of our projects this function and to display polygon layers. It would be perfect if we add the milestone v0.1.0 to this issue.

**Comment by MGlauer** [comment]
This has been implemented in https://github.com/tom-heimbrodt/oeplatform/commit/349fc87be4ef441f38b8d73576a2abd95d1c226e and will be part of the next release

**Comment by wolfbunke** [comment]
Nice, thank you!

**Comment by wolfbunke** [comment]
At the moment there are no Geometries at all mapped. 
Maybe this SQL Code can help:
`ST_AsGeoJSON(ST_Transform(geom,4236))` ?

**Comment by Ludee** [comment]
Map features have a high priority!

**Comment by MGlauer** [comment]
Polygons are visible in the corresponding branch - yet, it is still in development how to display them decently while keeping the datasize reasonable. Which is discussed in #248. Hence, I will close this issue.
