### ISSUE TITLE
data edit leads to server error

### ISSUE THREAD

**Issue by tillmo** [openego/oeplatform#118]
http://193.175.187.164/dataedit/view/geo_ego_jg
gives a 500 error

**Comment by MGlauer** [comment]
This schema is owned by the wrong database user. I informed the respective owner.

**Comment by tillmo** [comment]
for such server errors, there could be a friendlier page that also has a link redirecting to the platform

**Comment by tillmo** [comment]
OK, turned this comment into a separate issue, see #121
