### ISSUE TITLE
Data input should support foreign keys

### ISSUE THREAD

**Issue by MGlauer** [openego/oeplatform#12]
The current input scheme assumes that each a table draws the data directly from the table. The following is currently not possible:

| id | name |
| --- | --- |
| 1 | Marc |

| id | job | employee |
| --- | --- | --- |
| 2 | knitting | Marc |

Suppose the following input data: "Marc is knitting."

This "Marc" could not be linked to the id 1 with the current interface. 
Solution:
Add a 'link to prim. key where name = "Marc"' option to the mapping page of data-edit

**Comment by AemanMalik** [comment]
Ok, I have modified it. Just to clarify, can you please once explain what you mean by 'mapping page of data-edit'?

**Comment by MGlauer** [comment]
This is about the branch feature/data-edit that got merged into the develop branch yesterday. It is about the import of external data. 

Users are able to insert data into our database via a Webinterface. This interface is currently unable to handle foreign keys correctly.
