### ISSUE TITLE
server error after log in

### ISSUE THREAD

**Issue by tillmo** [openego/oeplatform#120]
When I log in with my credentials, I get a 500 server error (at http://193.175.187.164/login/)

**Comment by buddih09** [comment]
I have the same problem. Keep getting 500 server error.

**Comment by MGlauer** [comment]
Oh, seems like a database migration was not merged, yet. Will fix this asap.

**Comment by buddih09** [comment]
Thank you. Now I can log in but the download button ´went missing. 
http://oep.iks.cs.ovgu.de/dataedit/view/demand/ego_dp_loadarea
This is the data that I'm trying to extract.
