### ISSUE TITLE
sorting database tables does not work

### ISSUE THREAD

**Issue by tillmo** [openego/oeplatform#123]
At http://193.175.187.164/dataedit/view/orig_geo_powerplants/renewable_power_plants_germany, 
when I click on a column (like electrical_capacity), nothing happens.

**Comment by tillmo** [comment]
has this been deployed? For me, it still does not work.

**Comment by MGlauer** [comment]
Github closes automatically because of the commit message even. But the change is still on our devevelop branch, whilst the actually released platform runs on the latest master branch. 

I will migrate this fix asap.

**Comment by MGlauer** [comment]
It should be online now.

**Comment by tillmo** [comment]
understand. Works now!
