### ISSUE TITLE
Hide non-standard schemas

### ISSUE THREAD

**Issue by MGlauer** [openego/oeplatform#127]
There should be fewer schemas. Hide all schemas that are not listed below:

• Political Boundary (vg250; gn250; gadm)
• Power Plants (OPSD; BNetzA; EnergyMap)
• Electricity Grid (subs/TP; EHV/HV/MV/LV-grids; GD; powerflow)
• Demand (LA; load, consumption;
• Social (Zensus; destatis,
• Environmental (Landuse: clc, dlm, osm)
• Emissions (?)
• Economic (IÖR)

**Comment by Ludee** [comment]
Implemented in the white list!
