### ISSUE TITLE
Tag types

### ISSUE THREAD

**Issue by MGlauer** [openego/oeplatform#128]
It might be good to have several tag types are colored in shades of a common color. Possible tag types might be:
- Model tag: Data that belongs to a special model
- Data tag: Data that represents a special fact (e.g. powerplant data)

**Comment by Ludee** [comment]
I can suggest a [color wheel tool by adobe ](https://color.adobe.com/de/create/color-wheel/?base=2&rule=Monochromatic&selected=4&name=Mein%20Color-Thema&mode=rgb&rgbvalues=0,0.5,0.3242068059458916,0.30000000000000004,1,0.7538895283242482,0,1,0.6484136118917831,0.15000000000000002,0.5,0.3769447641621241,0,0.8,0.5187308895134265&swatchOrder=0,1,2,3,4)to find nice sets.
Is it possible to change a color for a tag?

**Comment by Ludee** [comment]
Colours are implemented by category.
