### ISSUE TITLE
Suggestion: Schema Sandbox

### ISSUE THREAD

**Issue by EvaWie** [openego/oeplatform#142]
In the sandbox the users can experiment with data. All created tables will be deleted on weekly basis e.g. Saturday at 6 pm.

@Ludee and @beritRLI Do we want to discuss this or are we convinced and want to implement it?

**Comment by EvaWie** [comment]
@openego/data_processing: Do we want to have a sand box, as suggested at the workshop?

**Comment by MGlauer** [comment]
Yes, this is a planned feature
