### ISSUE TITLE
Platform: Startpage and Fact Sheet Overview

### ISSUE THREAD

**Issue by EvaWie** [openego/oeplatform#150]
The text on the Djano start page only refers to the Fact Sheets.
Suggestion: Move this text to a new page (Fact Sheets - Overview) showing this introduction and the overview of all three types of fact sheets (3 lists). Replace the link to the discussion in the openmod wiki by a link to platform GitHub.

**Comment by EvaWie** [comment]
Do we connect us to the openmod start page or do we design our own start page? In case of the second option: Who is going to write the texts until when?

**Comment by beritRLI** [comment]
As far as we planned we want to put it on the openmod start page. @MGlauer  you still needed a right to put it there? or login data? if this is still missing we should try to accelerate communication about that.

**Comment by beritRLI** [comment]
I agree to Evas suggestion to move the Factsheet introduction to a (still not existing) page where you come to if you just click factsheets and not a special one.

**Comment by beritRLI** [comment]
Start page of Fact Sheets (Model, Framework, Scenario): the fact sheets should be in an understandable order (my suggestion: alphabetical) and then I can filter by tags.
As soon as more models appear there  the way it is now is very unconfortable
