### ISSUE TITLE
Scenario bundles: cannot add models from model factsheets 

### ISSUE THREAD

**Issue by han-f** [openego/oeplatform#1500]
## Description of the issue

There are several models available via the model factsheets that I cannot add so scenario bundles (e.g. ENUSEM). I thought I had already posted an issue about this, but cannot find it anymore.

If yes, what is the status? Is this something that can be fixed rather soon? I think it would be really helpful to be able to select from all model available under model factsheets. 

## Steps to Reproduce
1. Edit a scenario bundle
2. Navigate to models 
3. Try to add ENUSEM from the drop-down. 

## Ideas of solution
I do not have an idea how this can be fixed. 
## Context and Environment
* Version used: 
* Operating system: 
* Environment setup and (python) version: 

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

fyi @wingechr

**Comment by jh-RLI** [comment]
I can't find it either, maybe we discussed this as part of another problem. 

The error you describe occurs regularly when someone creates a new model/frame factsheet. The list you are looking for/seeing in the scenario bundle is a static list that only contains the factsheets that were available at the time the list was created. 

Adel updated the list last week and it will be available with the next release (this week ... I just realized that my notification email was not sent last week). I will check if ENUSEM is availabe in that updated list.

**Comment by jh-RLI** [comment]
The static files i talked about they are available here:

https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/factsheet/frontend/src/data/models.json
https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/factsheet/frontend/src/data/frameworks.json

**Comment by adelmemariani** [comment]
The "ENUSEM" is not contained in the lists. @han-f Could you recall when the ENUSEM model was added to the OEP? Was it recently added?

Currently, the lists for models and frameworks are being updated manually (in each release), therefore it is not dynamic. A permanent solution requires APIs for retrieving the updates.

**Comment by han-f** [comment]
ENUSEM was already available a long time ago by @l-emele, I only extended its information. This is why I was surprised to not find it in the list.

**Comment by adelmemariani** [comment]
I just checked and saw that ENUSEM exists in the list not by its acronym, but by its name:  [Energie-Umwandlungs-Sektor-Modell](https://openenergy-platform.org/factsheets/models/275)

**Comment by l-emele** [comment]
If that is the case, the selection field should use both the model name and the acronym. Maybe in a pattern like `abbreviation: model name`

**Comment by adelmemariani** [comment]
We will implement this feature in a future release. But this will not be available in the next release(we have a release scheduled for today).

**Comment by stap-m** [comment]
> The error you describe occurs regularly when someone creates a new model/frame factsheet. The list you are looking for/seeing in the scenario bundle is a static list that only contains the factsheets that were available at the time the list was created.

I guess this depends on the API? 
It is important, that the bundles don't rely on a static list in the future anymore. Users should be able to directly link anything to a bundle without waiting for another release.
