### ISSUE TITLE
Platform: Headings and Tabs

### ISSUE THREAD

**Issue by EvaWie** [openego/oeplatform#151]
The 3 Fact Sheet pages do not have headings telling me, what kind of list I see.

In general, neither the pages show, which tab I am in, nor tell the headings, because they differ from the name in the tab. I believe users can get lost here.

The tab "Discussion" leads to the discussion on the fact sheets. I suggest to link to the platform GitHub, because we will probably not notice comments in the openmod wiki owing to the missing notification function. The same refers to the discussion link in the side bar.

Spelling of "Fact Sheets" in Tab does not reflect the agreement.

**Comment by beritRLI** [comment]
I absolutely agree that we should switch the FS Discussion to the gitHub!! (And arrange the discussion more clearly here)
