### ISSUE TITLE
Documentation on REST API not accessible

### ISSUE THREAD

**Issue by MichaelGeFr** [openego/oeplatform#1634]
## Description of the issue
The documentation of the REST API is not accessible. 

## Steps to Reproduce
1. Got to https://openenergyplatform.github.io/oeplatform/install-and-documentation/oeplatform-code/web-api/oedb-rest-api/?badge=latest
2. click on the link for the readthedocs documentation

## Ideas of solution

Checkt the links

- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
Hi @MichaelGeFr thanks for documenting this. We noticed this already, but unfortunately, I did not update the content of that page to make it more clear what is happening. We decided to deactivate our old REST-API documentation as it is very outdated. I will migrate it and update the content within the next few months.

Until then, we recommend taking a look at our courses / tutorials on how to work with the REST-API. 
https://openenergyplatform.github.io/academy/tutorials/

- [ ] To "fix" this for now, I will update the page you linked and guide the user to the tutorials.
