### ISSUE TITLE
Data / Meta Data: Conform with EU requirements

### ISSUE THREAD

**Issue by EvaWie** [openego/oeplatform#172]
e.g. INSPIRE

**Comment by beritRLI** [comment]
meinst du das: 
http://www.geodaten.niedersachsen.de/inspire/dt_metadata/metadaten-fuer-inspire-147891.html
?
Danke

**Comment by Ludee** [comment]
I had a look at the INSPIRE rules and the underlying European directives and ISO.
see [discussion in the data_processing](https://github.com/openego/data_processing/issues/23).

**Comment by Ludee** [comment]
The metadata is not "conform" but "compatible" in some ways. INSPIRE is just insane, will need +1 hour for a single table to gather all info.
