### ISSUE TITLE
PowerWoche Collection ( former Impressum and legal hedging)

### ISSUE THREAD

**Issue by MGlauer** [openego/oeplatform#174]
The OEP need an impressum and disclaimers regarding handling of personal data, cookies, uploaded data etc.

@wolfbunke and me are working on a concept on this.

**Comment by wolfbunke** [comment]
Hey Martin, do we have a meeting today about this topic? Let me know. Maybe so we can have a short phone talk around 15:00 o'clock?

**Comment by wolfbunke** [comment]
Hey Martin maybe a good example:
https://daten.rlp.de/
With:
* Nutzungsbedingungen
* Impressum
  * Herausgeber
  * Ansprechpartner
  * Technische Realisierung und Betrieb
* Datenschutzerklärung
* FAQ
* CKAN-API ?? -> our Api -> github.com / readthedocs?
* About us
  * OpenMod
  * open_eGo
  * Finanzierung + Logo BMWI
* [Open Knowledge Foundation](https://okfn.org/)
* [open Data](http://opendefinition.org/od/2.0/en/)
* Kontakt

We need to define the language (DE or EN, or both ?). This is a question which sounds easy but due to German law and the server is hosted in Germany I don’t know if only English is enough!?!

**Comment by wolfbunke** [comment]
I called the RLI. The "About us" text will be written by them. Next week we know more about the status of editing. It is connected the the homepage task.

One open question is if you @beritRLI could be the "Ansprechpartner" for the oep?

**Comment by wolfbunke** [comment]
Die Datenschutzerklärung ist sehr spezifisch und schwer festzulegen. Es bedarf eines Abklärung was technisch gespeichert und zur Verfügung gestellt wird. 

Ich orientiere mich gerade an den Texten von
* https://wikimediafoundation.org/wiki/Terms_of_Use/de
* https://daten.rlp.de/pages/datenschutzerklaerung

**Comment by MGlauer** [comment]
- [x] Nutzungsbedingungen
- [x] Impressum
  - [x] Herausgeber
  - [x] Ansprechpartner
  - [x] Technische Realisierung und Betrieb
- [x] Datenschutzerklärung
- [ ] FAQ -> Hidden until we collect questions to put there.
- [ ] CKAN-API @MGlauer
- [ ] About us @EdithaK
  - [ ] open_eGo 
  - [ ] Finanzierung + Logo BMWI
  - [ ] OpenMod
- [ ] [Open Knowledge Foundation](https://okfn.org/) @MGlauer
- [ ] [open Data](http://opendefinition.org/od/2.0/en/) @MGlauer
- [x] Kontakt

**Comment by EdithaK** [comment]
OK. It may take some time due to my workload

**Comment by EdithaK** [comment]
ToDos from Telko
[] Proofread • Home: https://github.com/openego/oeplatform/blob/feature/formulations/base/templates/base/index.html and About: https://github.com/openego/oeplatform/blob/feature/formulations/base/templates/base/about.html @wolfbunke 
[] Find place for OKF in Home or About @wolfbunke 
[] Find place for oeplatform/base/templates/base/terms_of_use.html (Suggestion: its a third page biside Home/About --- /terms of use @wolfbunke 
[] Read Terms of use @beritRLI @EdithaK
[] Write 4 lines about haw to use the litrature @wolfbunke 
[] Find out how we ca integrate an interactive graphic @EdithaK @günni
[] Write list with Filteroptions for FS @beritRLI Help: @EdithaK
[] Extract Information from the readMe for OEP @beritRLI 
[] Complete Tags in given oedb @Ludee 
[] Start FactSheets on ego-projects @Ludee 
[] Note "Langfristplanung OEP" in ticket for projectmeeting @wolfbunke 
[] Set up overview page for Discussion-overview-page @MGlauer 
[] Add Berit as contact @MGlauer

**Comment by wolfbunke** [comment]
update of working issues:
- [ ]  Redmine Ticket created
- [ ]  OKF Link Button at the bottom / footer of page
- [ ] update of term of use text  
* Please see: https://github.com/openego/oeplatform/blob/feature/formulations/base/templates/base/terms_of_use.html -> "Die Nutzerinnen und Nutzer der OpenEnergy Platform" and add additional points @EdithaK @beritRLI @MGlauer 
- [ ] Button of "Term of use" in footer next to the Suggestion of EdithaK

**Comment by wolfbunke** [comment]
Add a sentence to index.html -> 

> _This platform is mainly addresses at students, researcher and scientists in the field of energy modelling and analytics as well as interested persons in those fields. The_ platform provides great tools to make your energy system modelling process transparent!

**Comment by wolfbunke** [comment]
Nice text in about.html, thank you!

**Comment by wolfbunke** [comment]
Here my text for the literature part:

> This is an overview of references and literature that are available on this platform. If you are log in you can add new references to our database using a **BibTeX** file or manually. Every entry has a unique id that can be referenced inside the **OEDB**, in order to make your dataset more transparent in case of many references. The id number is displayed in gray starting with a hash and the id number (e.g **#1**).
> 
> Learn more about the BibTeX on Wikipedia (https://de.wikipedia.org/wiki/BibTeX ) or BibTeX (http://www.bibtex.org/de/). 
> 
> Use the green add button to **add** your references as file or fill your information manually. By clicking on a entry you can **edit** it. 

I am not sure where to place the text @MGlauer can you insert this text at the right place?

**Comment by beritRLI** [comment]
Thanks Wolf!
I only added minor corrections/changes. I would avoid to talk about "our" database and changed it to "the". log=> logged; a entry=> an entry

This is an overview of references and literature that are available on this platform. If you are logged in you can add new references to the database using a BibTeX file or manually. Every entry has a unique id that can be referenced inside the OEDB, in order to make your dataset more transparent in case of many references. The id number is displayed in gray starting with a hash and the id number (e.g #1).
Learn more about the BibTeX on Wikipedia (https://de.wikipedia.org/wiki/BibTeX ) or BibTeX (http://www.bibtex.org/de/).
Use the green add button to add your references as file or fill your information manually. By clicking on an entry you can edit it.

**Comment by wolfbunke** [comment]
thx

**Comment by beritRLI** [comment]
For the about page we agreed on: Link from the bottom of the pages and from the home page (side space?) to "about". (Dropdown and own navigation point was rejected after discussion)

**Comment by EdithaK** [comment]
Juchu, neue ToDos:
-[ ] Grafik machen und an Günni schicken @EdithaK
-[ ] Grafik im unteren Teil des "home" einbinden @gnn
-[ ] PP raus @EdithaK
-[ ] Die einleitenden Sätze Litrature über die Liste mit den Einträgen @MGlauer 
-[ ] Link KNF setzen @MGlauer 
-[ ] Ideen für OEP "webung" sammeln (neues Ticket) @EdithaK
-[ ] Tags in oedb prüfen @EdithaK
-[ ] Bei den Terms us use die "wie wir sind" - Punkte ergänzen oder Umgang finden @beritRLI 
-[ ] About im home verlinken @EdithaK
-[ ] beritSite-Link an martin @EdithaK

Beschluss:
About us kommt in die Fußleiste.

**Comment by EdithaK** [comment]
ToDos and Q for Thursday:

- where do we mention that the openmod password/account can be used? Should be exposed
- are there further suggestions for #198?

**Comment by MGlauer** [comment]
Discussion overview in: 
https://github.com/openego/oeplatform/blob/feature/formulations/base/templates/base/discussion.html

**Comment by EdithaK** [comment]
@Ludee: Please check the filter options the Berit created.

**Comment by EdithaK** [comment]
- [ ] finalize "read Me" @beritRLI 
- [ ] publish all Berit-text @MGlauer 
- [ ] html-ize the discussion text @EdithaK
- [ ] Integrate fact sheet overview @MGlauer 
- [ ] install drop down filter in Fact-sheets @MGlauer @gnn

**Comment by EdithaK** [comment]
Q: Pressemitteilung, who knows the details?
