### ISSUE TITLE
IPython on OEP

### ISSUE THREAD

**Issue by Ludee** [openego/oeplatform#177]
Can I has an IPython on the OEP?
I'm not sure how complicated it is and how it works exactly. 
But since there are some issues with the data processing it would be quite nice.
I would like to hear your opinions and experiences!

**Comment by nesnoj** [comment]
No experiences but...YEA! That'd be great!

**Comment by wolfbunke** [comment]
I found another nice solution: https://github.com/datacamp/datacamp-light . Which would perfectly feet for tutorials of our tool.  IPython or now Jupyter Notebook would be also great. https://jupyter.org/ . Before we start an integration we need to define the user groups, server memory usage per user and the use case.

**Comment by wolfbunke** [comment]
fyi: https://cdn.datacamp.com/dcl/standalone-example.html
