### ISSUE TITLE
Table requests via api

### ISSUE THREAD

**Issue by MGlauer** [openego/oeplatform#184]
Implement the Table requests via 
/api/{schema_name}/tables/{table_name}

Currently, I am restructuring the API on branch feature/api.
Extend this API by functionalities for table DDLs

GET: Already implemented in  34b1a47
PUT:   Create a new table
POST: Change the existing table

The changes issues by POST should not be applied to the table directly. Instead, develop a way to store these propositions in a separate data structure and implement a way that admins can apply these changes.

The syntax of the PUT-body should (preferably) be close to what is returned by GET.

There was a [discussion](https://wiki.postgresql.org/wiki/HTTP_API) in the Postgres-community that might be helpfull.

**Comment by johannwagner** [comment]
Supported Input (Abridged from GET)

```json
{
  "constraints": {
    "id_pkey": {
      "constraint_typ": "PRIMARY KEY",
      "definition": "PRIMARY KEY (id)",
    }
  },
  "columns": {
    "id": {
      "data_type": "integer",
      "is_nullable": "YES",
      "character_maximum_length": null
    },
    "name": {
      "data_type": "character varying",
      "is_nullable": "YES",
      "character_maximum_length": 100
    }
  },
  "name": "test99",
  "schema": "reference"
}
```

Every request to unsave http methods have to contain a "csrftoken".
This token is used to deny cross site reference forwarding.
In every request the header had to contain "X-CSRFToken" with the actual csrftoken.
The token can be requested at / and will be returned as cookie.

**Comment by johannwagner** [comment]
Supported Input for POST-Requests (Abridged from GET)
```json
{
  "type" : "column",
  "name" : "test_name",
  "newname" : "changed_name",
  "data_type": "character varying",
  "is_nullable": "NO",
  "character_maximum_length": 50
}
```
You have to include all information to change a column except 'newname'. If you add 'newname' to JSON the column will be renamed. If your 'data_type' does not accept a size, 'character_maximum_length' should be null.
Edit constraints is not supported yet.

Do you want me to include the following?

- [ ] Adding primary keys
- [ ] Removing primary keys
- [ ] Adding foreign keys
- [ ] Removing foreign keys
- [ ] Adding other constraints
- [ ] Removing other constraints

- [ ] Reduce values on input
- [ ] Force changing data types of columns

**Comment by MGlauer** [comment]
The changes done via the API should be shown at the corresponding table views - not on a separate part of the page. I.e.: Move the information displayed at Database -> API Changes to a small box in the right column of the table view.

**Comment by johannwagner** [comment]
You removed all api functionalities in your first commit to "/feature/api".
It is not able to display data with current branch.

**Comment by MGlauer** [comment]
Ah sorry, by view I did not mean the recline.js view but the page it is contained in. I reintroduced the legacy API to fix that the request from recline fail, though. The API changes should be listed in the right column (under the "Popular tags" box).

**Comment by johannwagner** [comment]
I moved the changes to the sidebar. 
Your commit does not fix the issue.

**Comment by MGlauer** [comment]
Could you create a separate ticket for this error? I will fix it.

**Comment by johannwagner** [comment]
Look at #188.

**Comment by johannwagner** [comment]
@MGlauer 

Should SQL-Exceptions, if an requested change could not be applied, be saved and displayed ?

**Comment by johannwagner** [comment]
- [ ] Add Rollback
- [ ] Documentation
- [ ] Use constraint definition in CREATE TABLE
- [ ] Store SQL Exceptions 
- [ ] Display SQL Exceptions
- [ ] BUG: Button is disabled on adding a new column.
- [ ] Testing
