### ISSUE TITLE
API: Add REST-full select

### ISSUE THREAD

**Issue by MGlauer** [openego/oeplatform#190]
`GET: schema/<schemaname>/tables/<tablename>/rows`

should function as a select statement. This should be as simple as possible - for all advanced features there will be a separate functionality. 
Just implement the basic features with REST-parameters:
- [x] choice of specific columns
- [x] where
- [x] order_by
- [x] limit
- [x] offset 

Joins and group by and functions are not necessary.

**Comment by johannwagner** [comment]
In Django there is no appropriate way to make url parts optional. 
1. Option
    - Introduce a null character and going with `schema/<schemaname>/tables/<tablename>/rows/where/<whereclause>/...`
2. Option
    - Using GET-Parameters and going with `schema/<schemaname>/tables/<tablename>/rows/?where='id=1'&limit=100`

@MGlauer

**Comment by MGlauer** [comment]
Option 2  is the way to go. 
For the sake of completion: Option 1 might be possible to implement optional url parts using regular expressions (i.e. `r'((?P<opt1>{\w})\/)?((?P<opt2>{\w})\/)?`. The get function would might look like this: `def get(request, opt1=None, opt2=None):` I did not test it, as it is not how we should do it and there are still many issues (e.g. the order of options is fixed).

**Comment by MGlauer** [comment]
The where clause should allow more than just the '=' [operator](https://www.postgresql.org/docs/9.3/static/functions-comparison.html). You might need to encode these operators. Thus - for the sake of consistency - this should also be done for '=', too.

**Comment by MGlauer** [comment]
None of the GET-parameters should be mandatory. 
If no columns are specified, the query should default to '*'.
If neither limit, offset, where, nor order by are selected just omit them. 
I.e. the default query should be 

> select * from \<schema\>.\<table\>;
