### ISSUE TITLE
Questions Editha und Berit

### ISSUE THREAD

**Issue by beritRLI** [openego/oeplatform#194]
is literature a schema of the DB? how it is connected if not?
wie werden FS geordnet? (=> alphabetisch)
Sind schon Filterfunktionen in Arbeit? (OS, aktive,...)
Wie können wir interaktive grafiken machen?
Wohin packen wir Informationen zum Aufbau der Plattform (CKAN, Django,...) und dazu wie man mitgestalten/mitdiskutieren kann (Link zum GitHub (Issues, Code,..)?  => Oberseite bei Diskussion und Verweis auf Diskussion von Home oder About?

**Comment by beritRLI** [comment]
Hier unser Textplan:
OEP
•	Home: Funktion Website; Grafik zum Anklicken (Richtung DB, FS,…)
•	About: welche Projekte stehen dahinter, können sich einbringen (haben sich schon eingebracht (Reprod. WS)),…
DB:
Ein Satz auf erster Seite drüber mit Link zu Extra Seite; 
rechte Spalte mit Kurzerklärung Schema und Tags
Extra Seite mit genaueren Erklärungen
FS
Übergeordnete Seite mit Erklärung zu Umgang (Grafik zu Zusammenhang FSs + links)
Jede FS Seite starten mit kurzer Definition und notwendige Erklärungen im rechten Feld
Literatur
Müssen wir erst mal verstehen, dann Texte
Wiki = umbenennen in openmod wiki

**Comment by beritRLI** [comment]
#174

**Comment by beritRLI** [comment]
@MGlauer : though in german... could you include the links where we can put the texts in the "Textplan" above?

**Comment by MGlauer** [comment]
OEP
• Home: https://github.com/openego/oeplatform/blob/feature/formulations/base/templates/base/index.html
• About: https://github.com/openego/oeplatform/blob/feature/formulations/base/templates/base/about.html

DB:
ToDo

FS
Overview page: https://github.com/openego/oeplatform/blob/feature/formulations/modelview/templates/modelview/overview.html
List of Model/Framework/Scenario-FS (Depending on `{{label}}`): 
https://github.com/openego/oeplatform/blob/feature/formulations/modelview/templates/modelview/modellist.html

**Comment by EdithaK** [comment]
@MGlauer : this is the contact link to Berit. http://reiner-lemoine-institut.de/ueber-uns/team/berit-mueller/ . Would be great if you can integrate it.
