### ISSUE TITLE
Create interactive grafik for "home"

### ISSUE THREAD

**Issue by EdithaK** [openego/oeplatform#197]

**Comment by EdithaK** [comment]
@gnn: 
The .svg graphic will be done together with my collogue Miriam. Guess it not ready before 18:00 o'clock.

**Comment by gnn** [comment]
Ok. No biggie. Send it to me via mail when you're done. Maybe I'll have a look at it in the evening.

**Comment by EdithaK** [comment]
I made it! See your in-box. *excited*
P.S: nice profile-icon

**Comment by beritRLI** [comment]
what you mean by inbox? I want to see it!

**Comment by EdithaK** [comment]
@beritRLI die Änderungen sind das Resultat von er Absprache mit Ludwig.

**Comment by EdithaK** [comment]
Design Wishlist:

- [ ] Schrift schärfer (dont use bold)
- [ ] Arrows should be rounder and bold
