### ISSUE TITLE
Test the API

### ISSUE THREAD

**Issue by MGlauer** [openego/oeplatform#210]
There should be unit-tests for the API to ensure it's functionality. We decided to use the unittest and doctest frameworks. (I just checked node2 and its Django integration does not seem to work as good as it should)

There is also something on test in the [Django documentation](https://docs.djangoproject.com/en/1.11/topics/testing/tools/)

**Comment by johannwagner** [comment]
I am stuck with the database problem I mentioned in our talk. 
I can use another db for testing, but I have to make sure, that the DB is empty. There is no apropitate way to clear a database, so I thought about clearing a schema, which is pretty easy accoring this article: http://stackoverflow.com/questions/3327312/drop-all-tables-in-postgresql

Can I just use one schema for testing my function or is there a need for testing in more than one schema ?

**Comment by MGlauer** [comment]
There should be more than one schema - but not necessarily  an arbitrary number of them. Two should be sufficient in order to test cross-schema-functionalities. 
As we have a [fixed set of schemas](https://github.com/openego/oeplatform/blob/develop/dataedit/views.py#L39) (including model_draft and public) but apart from those no other schemas should be present.
