### ISSUE TITLE
Revisit existing factsheets and add open_ego tools

### ISSUE THREAD

**Issue by MGlauer** [openego/oeplatform#214]
The current factsheets require some work. Also, we should add some of our eGo tools:

- [x] Renpass-GIS
- [x] DINGO
- [x] eTraGo
- [ ] eDisGo (not jet)
- [ ] oemof
- [x] dataprocessing

**Comment by wolfbunke** [comment]
I take care of the renpassG!S sheets

**Comment by wolfbunke** [comment]
Inserted [renpassG!S](http://193.175.187.164/factsheets/models/43/) Model in Fact Sheets. I am waiting for feedback by renpassG!S members.

**Comment by EdithaK** [comment]
Ludee made a data processing FS.
We deleted the default-eGo FS, because it described the project instead of the tool.
FS we should keep in mind for later: ScenarioFS; eDisGo; eGo

**Comment by wolfbunke** [comment]
ok, thank you!

**Comment by EdithaK** [comment]
Caroline will Check the oemof FS. --> I close the Ticket
