### ISSUE TITLE
Warning when leaving the add fact sheet site

### ISSUE THREAD

**Issue by EvaWie** [openego/oeplatform#23]
Please, make sure, that a warning appears, when someone leaves the page, on which she/he creates a new fact sheet, without saving.

**Comment by MGlauer** [comment]
All factsheets are part of the "modelview" app. @quentinpeyras: Please adapt the edit{framework, model, scenario}.html so that users are warned, if they leave the page (seemingly unintended).

**Comment by EvaWie** [comment]
I do not believe that it worked out.

**Comment by MGlauer** [comment]
Yes, it did. The server was just not up to date. Issues close as soon as the commit is merged into the develop branch. The actual server is on the state of the last release on master branch.
