### ISSUE TITLE
Group management does not work

### ISSUE THREAD

**Issue by cswh** [openego/oeplatform#241]
When hitting "Delete Group" button on

https://oep.iks.cs.ovgu.de/user/groups/.../members

or trying to edit group name on

https://oep.iks.cs.ovgu.de/user/groups/.../edit

the following error occurs:

```
Sorry, something went wrong!

An unexpected error occured while processing your request. The admin has been informed about this incident.
For further information use our contact form.

Thanks a lot for your feedback! 
```

**Comment by MGlauer** [comment]
This bug seemed to origin from a single user that had multiple entries in one group. This state is not allowed by django. I fixed the respective entry in the database and also fixed (816a3f85) the presumed bug that led to this behaviour.
