### ISSUE TITLE
Successfull PUT and DELETE requests return empty response

### ISSUE THREAD

**Issue by s3pp** [openego/oeplatform#246]
Is this intended or should there be some kind of message?

Testet with:

<pre>

curl -X DELETE -H 'Content-Type: application/json' -H 'Authorization: Token ...' oep.iks.cs.ovgu.de/api/v0/schema/model_draft/tables/buergen_test/

curl -X PUT -H 'Content-Type: application/json' -H 'Authorization: Token ...' -d '{"query": { "columns": [{"name":"id", "data_type": "Bigserial","is_nullable": "NO"}, {"name":"name", "data_type": "varchar", "character_maximum_length": "50"}], "constraints": [{"constraint_type": "PRIMARY KEY", "constraint_parameter": "id"}]}}' oep.iks.cs.ovgu.de/api/v0/schema/model_draft/tables/buergen_test/

curl -X PUT -H "Content-Type: application/json" -H 'Authorization: Token ...' -d '{"query": {"name": "John Doe"}}' oep.iks.cs.ovgu.de/api/v0/schema/model_draft/tables/buergen_test/rows/1

</pre>

**Comment by MGlauer** [comment]
The result of a PUT or DELETE does not need any content apart from the status code. 
A 200 or 201 status should be sufficient.

What kind of content would you expect?

**Comment by s3pp** [comment]
Ah I see imo also that's totally sufficient! I had the impression in our discussion yesterday, that an empty response were in any case unexpected, that's why I pointed it out. Must have been a misunderstanding, thanks for clarifying!
