### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by cswh** [openego/oeplatform#247]
We made a small test for a visualisation based on the api at https://energiekollektiv.github.io/oep-vis-test/

However when trying to send a POST request via ajax, we get the following error:

`energiekollektiv.github.io/:1 Failed to load https://oep.iks.cs.ovgu.de/api/v0/schema/model_draft/tables/buergen_geo_district/: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://energiekollektiv.github.io' is therefore not allowed access.`

Could you give access to https://energiekollektiv.github.io or do we have to change something in the request?

**Comment by MGlauer** [comment]
Actually, this is not a bug but a feature. 
This happens, because your site requests data from a different server. This ist prohibited by many browsers due to security issues. 
I guess we can lift the CORS constraints for this the /search resource

**Comment by cswh** [comment]
> But I guess we can lift the CORS constraints for the /search resource

That would be great. Is it much to do on your side?

**Comment by cswh** [comment]
Ok. No CORS error anymore. But I get:

```
...
An unexpected error occured while processing your request.
The admin has been informed about this incident.
...
```

Should be reproducible with:
```
curl -X POST -H "Content-Type: application/json" --data '{"query": {"fields": ["id", {"type": "function", "function": "ST_AsText", "operands":[{"type": "function", "function": "ST_Transform", "operands": [{"type": "column", "column": "geom"}, 4326]}]}], "from":{"type": "table", "table": "buergen_geo_district", "schema":"model_draft"}}}' https://oep.iks.cs.ovgu.de/api/v0/advanced/search/
```

I am 99% sure that the same request via curl did work last week.

**Comment by s3pp** [comment]
Not sure why but it seems like the SRID was not set correctly while recreating the table. I will further investigate. In the meantime you can rely on buergen_geo_test for development. This should work as expected.

**Comment by MGlauer** [comment]
Yes, this was caused by missing SRIDs. I will add an error message.
