### ISSUE TITLE
MF Coverage

### ISSUE THREAD

**Issue by EvaWie** [openego/oeplatform#29]
There are a few points to improve the coverage section of the model fact sheet:

- the headlines grouping the options of "Modelled energy carriers (primary energy carriers)", "Modelled technologies: components for generation or conversion", "Modelled technologies: components for storage"

- the options of "Modelled technologies: components for transfer, infrastructure or grid" were specified unclear: electricity (transmission; distribution); heat (transmission; distribution); gas (transmission; distribution); Please, include the headings.

- Network coverage / representation (electrical grid): option "net transfer capacities" is missing

- "Changes in efficiency" text field is totally missing

- Market models was meant to be a check box, when yes: two options: fundamental model; stochastic model

- missing info text for "Geographical coverage": "What regions are covered? Please, list the regions covered by the model. Leave blank, if the model and data are not limited to a specific region.
Example input: USA, Canada, Mexico"

- Time resolution was accidentally called "Network coverage / representation (electrical grid)"

- "Additional dimensions (sector)": Please, delete "(sector)" from the heading. the text fields have unnecessary / unclear labels. Please, delete / replace them.

**Comment by MGlauer** [comment]
Market models should be a drop down with fundamental model; stochastic model; None
to be more consistent.
