### ISSUE TITLE
Scenario Fact Sheet - general information - Economic (behavioural) rationale

### ISSUE THREAD

**Issue by EvaWie** [openego/oeplatform#55]
Suggestions from the openmod wiki:
- If more tools/models are used it could be necessary that one has the possibility to put the model in the top and the the check boxes for each model.
- Appearance: On the right side there is a lot of space and the writing is left in too many lines

**Comment by EdithaK** [comment]
@beritRLI this is very old. I guess this is already resolved. I close it now. Do you need the info from Eva?
