### ISSUE TITLE
Fact Sheets: check boxes

### ISSUE THREAD

**Issue by EvaWie** [openego/oeplatform#57]
Design / Layout: Please, make sure that the user easily sees, which check box belongs to which text.

**Comment by MGlauer** [comment]
These irritations mostly origin from too long field names (e.g. "Decisions simulated by modeller due to qualitative criteria (spread-sheet simulation)").
We should rename those.

**Comment by EvaWie** [comment]
Please, try to make the space for the text a little bit wider in order to avoid all these line breaks. We will nevertheless discuss suggestions for shorter texts. The text standing in parenthesis could for instance become information text (accessible via the question marks).

**Comment by EdithaK** [comment]
Had a look at it. Everything was easy to understand. Thanks!
