### ISSUE TITLE
Split scenario Factsheets

### ISSUE THREAD

**Issue by MGlauer** [openego/oeplatform#59]
Currently, the section "Basic Information" contains informations regarding the study that contains the scenario. Studies can contain several scenarios.

Hence, we should remove the fields in basic information and put them into a seperate fact sheet.
On the form's "General Information" tab users can select from existing studies or select to enter a new one. If they do so, after submitting the form they are redirected to a new form for the new study. 

The actual fact sheet should look like it does now, but fetch the "General Information" from the new study table.

@EvaWie: Are there other fields that should be part of the study?

**Comment by EvaWie** [comment]
No, I do not think so.
@ludee: What do you think?

**Comment by ludee** [comment]
I'm not sure if I understand the new concept completely. 

What's about Scenarios that are not included in a published Study?
Is it still possible to add "General/Basic Infos"?

I can't find a field "Date of publication" of the study. 
Does the Scenario need a "Date of creation".

Let's invide @BeritRLI

**Comment by MGlauer** [comment]
@quentinpeyras There should be no actual "study" Fact Sheets as a seperate site or menu point. 
The content of the study Fact Sheet should  shown iff the user scenario Fact Sheet opens a scenario Fact Sheet  of a scenario that is analysed in this study.

I.e. the actual study fact sheet (not the edit form) should look like it did before but load the data from two tables (namely scenario+study).

The edit forms look good - except for these errors that seem to origin from missing fields. But i guess this is still in development. 
![error_scenario](https://cloud.githubusercontent.com/assets/7835111/14885848/11fed8d8-0d4e-11e6-8654-cfaaa347355d.png)

**Comment by quentinpeyras** [comment]
@MGlauer 
Then to edit a study factsheet the user should edit a scenario factsheet part of this study and edit some fields related to the study factsheet ?
And Should I allow creating new study by editing an existing scenario ?
In that case user should choose between 3 options, select an existing study, create a new study or edit the selected study.
About these errors I have them on my platform only if i select an other choice than "not estimated' without filling the corresponding field maybe I misunderstood how these fields should be checked.

**Comment by MGlauer** [comment]
Oh, it seems that this errors occurs only if you edit an existing scenario. The "Assumtions" tab is not even selectable in the edit. 

It might be good to add an extra button "edit study" next to the "edit" button on the scenario FS. As I wrote: the edit forms should be separated (as they are in you commited version).
