### ISSUE TITLE
Model Fact  Sheets - network coverage

### ISSUE THREAD

**Issue by EvaWie** [openego/oeplatform#87]
Because of the term "network coverage", which we do not use anymore, because it was misleading, we came to the following question:
Do we want to ask for the coverage of different networks?
gas
district heating grid
electricity
pipelines for oil
...
@ludee , what do you think?

**Comment by ludee** [comment]
Yes, we want to know the coverage of different networks. The focus should be on the relevant technologies that are already listed (electricity, heat, gas). pipelines for oil are not relevant.

**Comment by EvaWie** [comment]
Conclusion: No changes needed.
